version: "2"

# basic run config
run:
  timeout: 5m
  tests: true

# Enabled linters
linters:
  enable:
    - revive      # general linter
    - gocritic    # opinionated checks
    - gosec       # security focus
    - gocyclo     # complexity
    - gocognit    # cognitive complexity
    - misspell    # typo check
    - nolintlint  # check for unnecessary nolints
    - unconvert   # redundant type casts
    - prealloc    # slice growth efficiency

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  revive:
    # disable mandatory doc comments for everything
    rules:
      - name: exported
        disabled: true
    confidence: 0.8

issues:
  exclude-rules:
    # tests can be a bit more complex/messy
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - gosec
