version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
  path-prefix: ""
linters:
  enable:
    - bodyclose
    - copyloopvar
    - misspell
    - revive
    - whitespace
issues:
  max-same-issues: 100
  fix: true
  exclude-rules:
    - linters:
        - revive
      path: example_test.go
      text: seems to be unused
    - linters:
        - revive
      text: package-comments
  exclude-dirs:
    - examples
    - local
    - third_party
