version: "2"

run:
  issues-exit-code: 1
  tests: true

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  path-prefix: ""

linters:
  enable:
    - bodyclose
    - copyloopvar
    - misspell
    - revive
    - whitespace
    - unused
    - unparam
    - staticcheck

issues:
  max-same-issues: 100
  fix: true
  exclude-rules:
    - linters: [revive]
      path: example_test.go
      text: "seems to be unused"
    - linters: [revive]
      text: "package-comments"
  exclude-dirs:
    - local
    - third_party
    - builtin
    - examples

formatters:
  enable:
    - gofumpt
    - goimports