version: "2"

linters:
  enable:
    - revive
    - gocritic
    - gosec
    - gocyclo
    - gocognit
    - misspell
    - nolintlint
    - unconvert
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  revive:
    confidence: 0.8

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - gosec

run:
  timeout: 5m
  tests: true
